version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
      MEDIA_ROOT: /data/media
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.tasks.celery_tasks worker --loglevel=info
    volumes:
      - ./:/app
      - ./data:/data
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  db_data:
